version: '3.8'
services:
  firebase-emulator:
    build:
      context: .
      dockerfile: dockerfile-emulator
    ports:
        - "4000:4000" # Realtime Database
        - "9099:9099" # Authentication

  app:
    build:
      context: .
      dockerfile: dockerfile-app
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_db
    volumes:
      - ./db:/var/run/mysql
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  my-network:
