version: '3.8'
services:
  firebase-emulator:
    image: spine3/firebase-emulator
    ports:
      - "4000:4000" # Realtime Database
      - "9099:9099" # Authentication

    volumes:
      - ./firebase/firebase.json:/firebase.json
      - ./firebase/emulator-entrypoint.sh:/emulator-entrypoint.sh

    environment:
      GCP_PROJECT: "art-share"
      ENABLE_UI: "true"
    entrypoint: [ "bash", "/emulator-entrypoint.sh" ]

  app:
      build:
          context: .
          dockerfile: dockerfile-app
      ports:
          - "8080:8080"
      volumes:
          - ./src:/app/src
          - ./.gradle/caches:/root/.gradle/caches
      environment:
          - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
      env_file:
          - .env
      depends_on:
          mariadb:
              condition: service_healthy
      restart: unless-stopped

  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      MYSQL_DATABASE: my_db
    volumes:
      - ./db:/var/run/mysql
    ports:
      - "13306:3306"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  my-network:
