spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: "jdbc:h2:mem:my_db;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui
    display-request-duration: true

  cache:
    disabled: true

firebase:
    admin-sdk:
        path: 'dummy_path'
cloud:
    aws:
        credentials:
            access-key: "dummy_key"
            secret-key: "dummy_key"
        stack:
            auto: false
        region:
            static: kr-standard
        s3:
            endpoint: https://kr.object.ncloudstorage.com
            bucket: artshare
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:mysql://localhost/library"
    username: ${SPRING_DATABASE_NAME}
    password: ${SPRING_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  flyway:
      enabled: true
      baseline-on-migrate: true

  jpa:
      hibernate:
          ddl-auto: create
      properties:
          hibernate:
              show_sql: true
              format_sql: true
              dialect: org.hibernate.dialect.H2Dialect

springdoc:
    api-docs:
        path: /api-docs

    swagger-ui:
        path: /swagger-ui
        display-request-duration: true

firebase:
    admin-sdk:
        path: '${user.dir}/firebase/firebase-admin.json'

cloud:
  aws:
    credentials:
      access-key: ${NAVER_CLOUD_ACCESS_KEY}
      secret-key: ${NAVER_CLOUD_SECRET_KEY}
    stack:
      auto: false
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: artshare
