spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: "jdbc:h2:mem:my_db;MODE=MYSQL;NON_KEYWORDS=USER"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui
    display-request-duration: true

  cache:
    disabled: true

firebase:
    admin-sdk:
        path: '${user.dir}/firebase/firebase-admin.json'

cloud:
    aws:
        credentials:
            access-key: ${NAVER_CLOUD_ACCESS_KEY}
            secret-key: ${NAVER_CLOUD_SECRET_KEY}
        stack:
            auto: false
        region:
            static: kr-standard
        s3:
            endpoint: https://kr.object.ncloudstorage.com
            bucket: artshare
---
spring:
    config:
        activate:
            on-profile: dev

    datasource:
        url: ${SPRING_DATABASE_URL}
        username: ${SPRING_DATABASE_USERNAME}
        password: ${SPRING_DATABASE_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver

    flyway:
        enabled: true
        baseline-on-migrate: true

    # JPA
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.MariaDB103Dialect

springdoc:
    api-docs:
        path: /api-docs

    swagger-ui:
        path: /swagger-ui
        display-request-duration: true

firebase:
    admin-sdk:
        path: '${user.dir}/firebase/firebase-admin.json'

cloud:
  aws:
    credentials:
      access-key: ${NAVER_CLOUD_ACCESS_KEY}
      secret-key: ${NAVER_CLOUD_SECRET_KEY}
    stack:
      auto: false
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: artshare
