spring:
    profiles:
        active: local
        include:
            - domain
            - external
management:
    metrics:
        tags:
            application: "art-share"
    endpoints:
        web:
            exposure:
                include: prometheus
