spring:
    profiles:
        active: local
        include:
            - domain
            - external
management:
    endpoints:
        web:
            exposure:
                include: prometheus
