build:
    maxIssues: 0
    excludeCorrectable: false
    weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1

config:
    validation: true
    # when writing own rules with new properties, exclude the property path e.g.: "my_rule_set,.*>.*>[my_property]"
    excludes: ""

processors:
    active: true
    exclude:
        - 'DetektProgressListener'
        # - 'FunctionCountProcessor'
        # - 'PropertyCountProcessor'
        # - 'ClassCountProcessor'
        # - 'PackageCountProcessor'
        # - 'KtFileCountProcessor'

console-reports:
    active: true
    exclude:
        - 'ProjectStatisticsReport'
        - 'ComplexityReport'
        - 'NotificationReport'
        #  - 'FindingsReport'
        - 'FileBasedFindingsReport'

comments:
    active: true
    excludes: '**/test/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt'
    AbsentOrWrongFileLicense:
        active: false
        licenseTemplateFile: 'license.template'
    CommentOverPrivateFunction:
        active: false

performance:
    SpreadOperator:
        active: false

style:
    MagicNumber:
        active: false
