name: Kotlin CI with Gradle and Kover

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'src/**'

jobs:
  checkstyle:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2
      - name: Run ktlint
        run: ./gradlew ktlintCheck

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle and Kover
        run: ./gradlew build koverHtmlReport
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ github.workspace }}/config/kover-html-result
      - name: Add coverage to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          coverage-counter-type: LINE
