name: Kotlin CI with Gradle and Kover

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'src/**'

jobs:
  checkstyle:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2

      - name: Run ktlint
        run: ./gradlew ktlintCheck

  build:
    permissions: write-all

    runs-on: ubuntu-latest

    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle and Kover
        run: ./gradlew build koverReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ github.workspace }}/build/reports/kover/report.xml
