name: Kotlin CI with Gradle, Kover, and Detekt

on:
    pull_request:
        branches: [ "main", "dev" ]
        paths:
            - 'src/**'
env:
    DETEKT_RELEASE_TAG: v1.15.0

jobs:
    checkstyle:
        runs-on: ubuntu-latest
        steps:
            -   name: Setting Checkout
                uses: actions/checkout@v2
            -   name: Run ktlint
                run: ./gradlew ktlintCheck

    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Setting Checkout
                uses: actions/checkout@v2

            -   name: create-json
                id: create-json
                uses: jsdaniell/create-json@v1.2.2
                with:
                    name: firebase-admin.json
                    json: ${{ secrets.FIREBASE_ADMIN_JSON }}
                    dir: firebase/

            -   name: Cache Gradle dependencies and build cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches/modules-2
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'

            -   name: Build with Gradle and Kover
                run: ./gradlew :art-api:build koverXmlReport

            -   name: Add coverage report to PR
                uses: mi-kas/kover-report@v1
                with:
                    path: ${{ github.workspace }}/config/kover-xml-result/report.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    title: Code Coverage

    detekt: # 추가된 detekt 작업
        runs-on: ubuntu-latest
        steps:
            -   name: Setting Checkout
                uses: actions/checkout@v2

            # Detekt 설치
            -   name: Setup Detekt
                run: |
                    dest=$( mktemp -d )
                    curl --request GET \
                      --url https://github.com/detekt/detekt/releases/download/${{ env.DETEKT_RELEASE_TAG }}/detekt-${{ env.DETEKT_RELEASE_TAG }}-all.jar \
                      --silent \
                      --location \
                      --output $dest/detekt
                    chmod a+x $dest/detekt
                    echo $dest >> $GITHUB_PATH

            # Detekt 실행
            -   name: Run Detekt
                run: detekt --input src --config config/detekt.yml --report txt:detekt-report.txt
