name: Deploy Images to GHCR and Kotlin CI with Gradle

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  checkstyle:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2
      - name: Run ktlint
        run: ./gradlew ktlintCheck

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle dependencies and build cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle and Kover
        run: ./gradlew build koverXmlReport

      - name: Add coverage report to PR
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/config/kover-xml-result/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage

  push-image:
    runs-on: ubuntu-latest
    needs: [ checkstyle, build ]
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Art Share Container image'
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/store:latest
          docker push ghcr.io/${{ github.repository_owner }}/store:latest
