name: Kotlin CI with Gradle and Kover

on:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'src/**' # listen to changes in src directory only

jobs:
  checkstyle:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2 # checkout the repository
      - name: Run ktlint
        run: ./gradlew ktlintCheck # run ktlint to check code style

  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setting Checkout
        uses: actions/checkout@v2 # checkout the repository
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches # cache Gradle dependencies
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # set up JDK 11
      - name: Build with Gradle and Kover
        run: ./gradlew build koverXmlReport # build the project and generate Kover report
      - name: Add coverage report to PR
        uses: mi-kas/kover-report@v1 # add Kover coverage report to PR
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 10 # set minimum coverage required for overall project
          min-coverage-changed-files: 10 # set minimum coverage required for changed files
          coverage-counter-type: LINE # set coverage counter type as LINE
