name: Project Cd

on:
    push:
        branches:
            - '#28-CI-/-CD-구축-리뉴얼'
    pull_request:
        branches:
            - 'main'
            - 'dev'
        paths:
            - '*'

jobs:
    Project CD:
        runs-on: ubuntu-18.04 # naver cloud os

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'temurin'

            - name: Create Firebase Json
              uses: jsdaniell/create-json@v1.2.2
              with:
                  name: firebase-admin.json
                  json: ${{ secrets.FIREBASE_ADMIN_JSON }}
                  dir: firebase/

            - name: Create Api Property yaml file
              run: |
                  cd ./art-api/src/main/resources
                  touch ./application.yaml
                  echo "${{ secrets.PROPERTIES_API}}" > ./application.yaml
              shell: bash

            - name: Create Domain Property yaml file
              run: |
                  cd ./art-domain/src/main/resources
                  touch ./application.yaml
                  echo "${{ secrets.PROPERTIES_DOMAIN}}" > ./application-domain.yaml
              shell: bash

            - name: Create External Property yaml file
              run: |
                  cd ./art-external/src/main/resources
                  touch ./application.yaml
                  echo "${{ secrets.PROPERTIES_EXTERNAL}}" > ./application-external.yaml
              shell: bash
