name: Project Cd

on:
    push:
        branches:
            - '#28-CI-/-CD-구축-리뉴얼'
            - 'main'

jobs:
    project_deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'

            -   name: Create Firebase Json
                uses: jsdaniell/create-json@v1.2.2
                with:
                    name: firebase-admin.json
                    json: ${{ secrets.FIREBASE_ADMIN_JSON }}
                    dir: firebase/

            -   name: Create Api Property yaml file
                run: |
                    mkdir -p ./art-api/src/main/resources
                    cd ./art-api/src/main/resources
                    touch ./application.yaml
                    echo "${{ secrets.PROPERTIES_API}}" > ./application.yaml
                shell: bash

            -   name: Create Domain Property yaml file
                run: |
                    mkdir -p ./art-domain/src/main/resources
                    cd ./art-domain/src/main/resources
                    touch ./application-domain.yaml
                    echo "${{ secrets.PROPERTIES_DOMAIN}}" > ./application-domain.yaml
                shell: bash

            -   name: Create External Property yaml file
                run: |
                    mkdir -p ./art-external/src/main/resources
                    cd ./art-external/src/main/resources
                    touch ./application-external.yaml
                    echo "${{ secrets.PROPERTIES_EXTERNAL}}" > ./application-external.yaml
                shell: bash

            -   name: Build with Gradle
                run: ./gradlew :art-api:build -Pspring.profiles.active=test -x test

            -   name: Docker build and registry
                run: |
                    echo "${{ secrets.REGISTRY}}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin

