name: Kotlin CI with Gradle, Kover, and Detekt

on:
    push:
        branches:
            - '*'
        paths:
            - '*'
    pull_request:
        branches:
            - 'main'
            - 'dev'
        paths:
            - '*'

jobs:
    checkstyle:
        runs-on: ubuntu-latest
        steps:
            -   name: Setting Checkout
                uses: actions/checkout@v2
            -   name: Run ktlint
                run: ./gradlew ktlintCheck

    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Setting Checkout
                uses: actions/checkout@v2

            -   name: Cache Gradle dependencies and build cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches/modules-2
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'

            -   name: Build with Gradle and Kover
                run: ./gradlew :art-api:build koverXmlReport

            -   name: Add coverage report to PR
                uses: mi-kas/kover-report@v1
                with:
                    path: ${{ github.workspace }}/config/kover-xml-result/report.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    title: Code Coverage

    detekt:
        runs-on: ubuntu-latest
        steps:
            -   name: Setting Checkout
                uses: actions/checkout@v2

            -   name: Cache Gradle dependencies and build cache
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.gradle/caches/modules-2
                        ~/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
                    restore-keys: |
                        ${{ runner.os }}-gradle-

            -   name: Set up JDK 11
                uses: actions/setup-java@v3
                with:
                    java-version: '11'
                    distribution: 'temurin'

            # Detekt 실행
            -   name: Run Detekt
                run: ./gradlew detektAll
